"""Change relation in Municipio because was with tipo_documento not departamento

Revision ID: 03a1901abaac
Revises: f2f99f6ba1e4
Create Date: 2025-06-01 17:31:56.200240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a1901abaac'
down_revision: Union[str, None] = 'f2f99f6ba1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('municipio_ibfk_1'), 'municipio', type_='foreignkey')
    op.create_foreign_key(None, 'municipio', 'departamento', ['departamento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'municipio', type_='foreignkey')
    op.create_foreign_key(op.f('municipio_ibfk_1'), 'municipio', 'tipo_documento', ['departamento_id'], ['id'])
    # ### end Alembic commands ###
