"""Try

Revision ID: 056c1454a895
Revises: 70e7bb5fdc27
Create Date: 2025-06-11 10:41:34.658602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056c1454a895'
down_revision: Union[str, None] = '70e7bb5fdc27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'respuesta', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'respuesta', type_='foreignkey')
    # ### end Alembic commands ###
