"""create certificacion_predio table

Revision ID: 1c13e0cba82a
Revises: ac130ca2a1b1
Create Date: 2025-06-28 21:29:17.345364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c13e0cba82a'
down_revision: Union[str, None] = 'ac130ca2a1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificacion_predio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('archivo_pdf', sa.String(length=255), nullable=True),
    sa.Column('fecha_expedicion', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['predio_id'], ['predio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificacion_predio_id'), 'certificacion_predio', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificacion_predio_id'), table_name='certificacion_predio')
    op.drop_table('certificacion_predio')
    # ### end Alembic commands ###
