"""Add tipo_documento table and update users

Revision ID: 3008b7048d19
Revises: ffba24432e7f
Create Date: 2025-06-01 16:24:42.239279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3008b7048d19'
down_revision: Union[str, None] = 'ffba24432e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tipo_documento_id'), 'tipo_documento', ['id'], unique=False)
    op.add_column('users', sa.Column('tipo_documento_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('num_documento', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'users', 'tipo_documento', ['tipo_documento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'num_documento')
    op.drop_column('users', 'tipo_documento_id')
    op.drop_index(op.f('ix_tipo_documento_id'), table_name='tipo_documento')
    op.drop_table('tipo_documento')
    # ### end Alembic commands ###
