"""When Delete Insumo delete the relation in Exportacion / Cosecha in ExportacionCosecha

Revision ID: 33fdfdeff9de
Revises: dd6218c47aba
Create Date: 2025-06-19 20:47:40.298031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33fdfdeff9de'
down_revision: Union[str, None] = 'dd6218c47aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exportacion_cosecha_ibfk_2'), 'exportacion_cosecha', type_='foreignkey')
    op.drop_constraint(op.f('exportacion_cosecha_ibfk_1'), 'exportacion_cosecha', type_='foreignkey')
    op.create_foreign_key(None, 'exportacion_cosecha', 'exportacion', ['exportacion_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exportacion_cosecha', 'cosecha', ['cosecha_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exportacion_cosecha', type_='foreignkey')
    op.drop_constraint(None, 'exportacion_cosecha', type_='foreignkey')
    op.create_foreign_key(op.f('exportacion_cosecha_ibfk_1'), 'exportacion_cosecha', 'cosecha', ['cosecha_id'], ['id'])
    op.create_foreign_key(op.f('exportacion_cosecha_ibfk_2'), 'exportacion_cosecha', 'exportacion', ['exportacion_id'], ['id'])
    # ### end Alembic commands ###
