"""Unidad Table

Revision ID: 5b43e6989d59
Revises: 33fdfdeff9de
Create Date: 2025-06-25 18:15:49.000031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b43e6989d59'
down_revision: Union[str, None] = '33fdfdeff9de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insumo', type_='foreignkey')
    op.drop_table('unidad')
    # ### end Alembic commands ###
