"""Add more chars to columns

Revision ID: 656326356da2
Revises: 8a7f56d0a946
Create Date: 2025-06-07 19:13:43.051130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '656326356da2'
down_revision: Union[str, None] = '8a7f56d0a946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exportacion', 'puerto_salida',
               existing_type=mysql.VARCHAR(length=70),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('exportacion', 'puerto_llegada',
               existing_type=mysql.VARCHAR(length=70),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('predio', 'direccion',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('usuario', 'direccion',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'direccion',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('predio', 'direccion',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('exportacion', 'puerto_llegada',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=70),
               existing_nullable=True)
    op.alter_column('exportacion', 'puerto_salida',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=70),
               existing_nullable=True)
    # ### end Alembic commands ###
