"""Add user.id to Respuestas

Revision ID: 70e7bb5fdc27
Revises: c665d5878773
Create Date: 2025-06-11 10:37:46.823572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e7bb5fdc27'
down_revision: Union[str, None] = 'c665d5878773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('respuesta', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'respuesta', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'respuesta', type_='foreignkey')
    op.drop_column('respuesta', 'usuario_id')
    # ### end Alembic commands ###
