"""Change columns in Users

Revision ID: 817187437560
Revises: 3008b7048d19
Create Date: 2025-06-01 16:42:35.661979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '817187437560'
down_revision: Union[str, None] = '3008b7048d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cedula')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cedula', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
