"""Change name User to Usuario

Revision ID: 960cb46635d5
Revises: d78bf74663da
Create Date: 2025-06-02 11:00:33.257945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '960cb46635d5'
down_revision: Union[str, None] = 'd78bf74663da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1️⃣ Eliminar la constraint que referencia a 'user'
    op.drop_constraint('predio_ibfk_2', 'predio', type_='foreignkey')

    # 2️⃣ Borrar la tabla 'user'
    op.drop_table('user')

    # 3️⃣ Crear la nueva foreign key que apunta a 'usuario'
    op.create_foreign_key(None, 'predio', 'usuario', ['usuario_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predio', type_='foreignkey')
    op.create_foreign_key(op.f('predio_ibfk_2'), 'predio',
                          'user', ['usuario_id'], ['id'])
    op.create_table('user',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('nombre', mysql.VARCHAR(
                        length=50), nullable=True),
                    sa.Column('tipo_persona', mysql.VARCHAR(
                        length=50), nullable=True),
                    sa.Column('razon_social', mysql.VARCHAR(
                        length=100), nullable=True),
                    sa.Column('telefono', mysql.VARCHAR(
                        length=50), nullable=True),
                    sa.Column('direccion', mysql.VARCHAR(
                        length=100), nullable=True),
                    sa.Column('pagina_web', mysql.VARCHAR(
                        length=100), nullable=True),
                    sa.Column('rut', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('logo', mysql.VARCHAR(
                        length=255), nullable=True),
                    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
                    sa.Column('tipo_documento_id', mysql.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('num_documento', mysql.VARCHAR(
                        length=50), nullable=True),
                    sa.Column('email', mysql.VARCHAR(
                        length=320), nullable=False),
                    sa.Column('hashed_password', mysql.VARCHAR(
                        length=1024), nullable=False),
                    sa.Column('is_active', mysql.TINYINT(display_width=1),
                              autoincrement=False, nullable=False),
                    sa.Column('is_superuser', mysql.TINYINT(display_width=1),
                              autoincrement=False, nullable=False),
                    sa.Column('is_verified', mysql.TINYINT(display_width=1),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['tipo_documento_id'], [
                        'tipo_documento.id'], name=op.f('user_ibfk_1')),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###
