"""Unidad Table 2

Revision ID: ac130ca2a1b1
Revises: 5b43e6989d59
Create Date: 2025-06-25 18:19:23.417927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac130ca2a1b1'
down_revision: Union[str, None] = '5b43e6989d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'insumo', 'unidad', ['unidad'], ['nombre'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insumo', type_='foreignkey')
    # ### end Alembic commands ###
