"""Change Proveedor realtions with Municipio and add columns

Revision ID: b0d3d2cb9d01
Revises: c25c9ffbf18c
Create Date: 2025-06-18 19:00:33.409385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0d3d2cb9d01'
down_revision: Union[str, None] = 'c25c9ffbf18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insumo', 'nombre_comercial',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=155),
               existing_nullable=False)
    op.add_column('proveedor', sa.Column('tipo_doc', sa.Integer(), nullable=True))
    op.add_column('proveedor', sa.Column('num_doc', sa.String(length=70), nullable=False))
    op.add_column('proveedor', sa.Column('ciudad', sa.String(length=70), nullable=True))
    op.add_column('proveedor', sa.Column('pais', sa.String(length=50), nullable=True))
    op.add_column('proveedor', sa.Column('direccion', sa.String(length=255), nullable=True))
    op.add_column('proveedor', sa.Column('contacto', sa.String(length=70), nullable=True))
    op.drop_constraint(op.f('proveedor_ibfk_1'), 'proveedor', type_='foreignkey')
    op.create_foreign_key(None, 'proveedor', 'tipo_documento', ['tipo_doc'], ['id'])
    op.drop_column('proveedor', 'municipio_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proveedor', sa.Column('municipio_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'proveedor', type_='foreignkey')
    op.create_foreign_key(op.f('proveedor_ibfk_1'), 'proveedor', 'municipio', ['municipio_id'], ['id'])
    op.drop_column('proveedor', 'contacto')
    op.drop_column('proveedor', 'direccion')
    op.drop_column('proveedor', 'pais')
    op.drop_column('proveedor', 'ciudad')
    op.drop_column('proveedor', 'num_doc')
    op.drop_column('proveedor', 'tipo_doc')
    op.alter_column('insumo', 'nombre_comercial',
               existing_type=sa.String(length=155),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
