"""Add calidad/producto/cosecha tables and their relations 

Revision ID: b3a6608eb417
Revises: 2764a6acb239
Create Date: 2025-06-02 17:03:42.282778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a6608eb417'
down_revision: Union[str, None] = '2764a6acb239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calidad_id'), 'calidad', ['id'], unique=False)
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_id'), 'producto', ['id'], unique=False)
    op.create_table('cosecha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('calidad_id', sa.Integer(), nullable=False),
    sa.Column('toneladas', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('hectareas', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('calibre_promedio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['calidad_id'], ['calidad.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cosecha_id'), 'cosecha', ['id'], unique=False)
    op.create_table('cosecha_predio',
    sa.Column('cosecha_id', sa.Integer(), nullable=False),
    sa.Column('predio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cosecha_id'], ['cosecha.id'], ),
    sa.ForeignKeyConstraint(['predio_id'], ['predio.id'], ),
    sa.PrimaryKeyConstraint('cosecha_id', 'predio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cosecha_predio')
    op.drop_index(op.f('ix_cosecha_id'), table_name='cosecha')
    op.drop_table('cosecha')
    op.drop_index(op.f('ix_producto_id'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_calidad_id'), table_name='calidad')
    op.drop_table('calidad')
    # ### end Alembic commands ###
