"""Change Proveedor columns

Revision ID: be2bbb2b2531
Revises: 2b04b6218b59
Create Date: 2025-06-02 20:48:58.100761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be2bbb2b2531'
down_revision: Union[str, None] = '2b04b6218b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('proveedor_ibfk_2'), 'proveedor', type_='foreignkey')
    op.drop_column('proveedor', 'tipo_doc')
    op.drop_column('proveedor', 'rut')
    op.drop_column('proveedor', 'num_doc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proveedor', sa.Column('num_doc', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('proveedor', sa.Column('rut', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('proveedor', sa.Column('tipo_doc', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('proveedor_ibfk_2'), 'proveedor', 'tipo_documento', ['tipo_doc'], ['id'])
    # ### end Alembic commands ###
