"""Add usuario_id in Exportación

Revision ID: c25c9ffbf18c
Revises: 056c1454a895
Create Date: 2025-06-18 18:49:01.080414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c25c9ffbf18c'
down_revision: Union[str, None] = '056c1454a895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exportacion', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exportacion', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exportacion', type_='foreignkey')
    op.drop_column('exportacion', 'usuario_id')
    # ### end Alembic commands ###
