"""Eliminate costo_uniario from InsumoCosecha

Revision ID: c665d5878773
Revises: 982431021469
Create Date: 2025-06-10 17:28:03.584827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c665d5878773'
down_revision: Union[str, None] = '982431021469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insumo_cosecha', 'costo_unitario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insumo_cosecha', sa.Column('costo_unitario', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###
