"""Delete stock column in Insumo

Revision ID: cc13d2fb1e44
Revises: be2bbb2b2531
Create Date: 2025-06-02 20:52:17.297029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc13d2fb1e44'
down_revision: Union[str, None] = 'be2bbb2b2531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insumo', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insumo', sa.Column('stock', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###
