"""Agregar longitud a RUT y logo

Revision ID: db9ab8fada96
Revises: 88327518c3d7
Create Date: 2025-05-30 22:16:01.335276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9ab8fada96'
down_revision: Union[str, None] = '88327518c3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('tipo_persona', sa.String(length=50), nullable=True),
    sa.Column('razon_social', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.Column('pagina_web', sa.String(length=100), nullable=True),
    sa.Column('rut', sa.String(length=255), nullable=True),
    sa.Column('cedula', sa.String(length=50), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
