"""When Delete Insumo delete the relation

Revision ID: dd6218c47aba
Revises: b0d3d2cb9d01
Create Date: 2025-06-19 20:29:50.956581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6218c47aba'
down_revision: Union[str, None] = 'b0d3d2cb9d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('insumo_cosecha_ibfk_2'), 'insumo_cosecha', type_='foreignkey')
    op.create_foreign_key(None, 'insumo_cosecha', 'insumo', ['insumo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'insumo_cosecha', type_='foreignkey')
    op.create_foreign_key(op.f('insumo_cosecha_ibfk_2'), 'insumo_cosecha', 'insumo', ['insumo_id'], ['id'])
    # ### end Alembic commands ###
