"""add tabla certificacion y FK en certificacion_predio

Revision ID: df5afb334b79
Revises: 1c13e0cba82a
Create Date: 2025-06-28 22:02:19.448948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'df5afb334b79'
down_revision: Union[str, None] = '1c13e0cba82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_certificacion_id'), 'certificacion', ['id'], unique=False)
    op.add_column('certificacion_predio', sa.Column('certificacion_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'certificacion_predio', 'certificacion', ['certificacion_id'], ['id'])
    op.drop_column('certificacion_predio', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificacion_predio', sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'certificacion_predio', type_='foreignkey')
    op.drop_column('certificacion_predio', 'certificacion_id')
    op.drop_index(op.f('ix_certificacion_id'), table_name='certificacion')
    op.drop_table('certificacion')
    # ### end Alembic commands ###
