"""Delete nombre columns in Usuario

Revision ID: e708d2b08e0b
Revises: cc13d2fb1e44
Create Date: 2025-06-03 19:11:32.420489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e708d2b08e0b'
down_revision: Union[str, None] = 'cc13d2fb1e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
