"""Add Municipio Departamento and Predio table change name of users to user

Revision ID: f2f99f6ba1e4
Revises: 18ab495df371
Create Date: 2025-06-01 17:07:32.226534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f2f99f6ba1e4'
down_revision: Union[str, None] = '18ab495df371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('cedula_catastral', sa.BigInteger(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('vereda', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.Column('hectareas', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('vocacion', sa.String(length=50), nullable=True),
    sa.Column('altitud_promedio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('tipo_riego', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula_catastral')
    )
    op.create_index(op.f('ix_predio_id'), 'predio', ['id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tipo_persona', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('razon_social', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('telefono', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pagina_web', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('rut', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('logo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=320), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('tipo_documento_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_documento', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipo_documento.id'], name=op.f('users_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_predio_id'), table_name='predio')
    op.drop_table('predio')
    # ### end Alembic commands ###
